export interface UserRank {
  id: number;
  nickname: string;
  rank: number; // 전체 순위 (봇 + 사람) //dd
  rankAmongBots?: number; // 봇들 중에서의 순위
  rankAmongUsers?: number; // 다른 사용자들 중에서의 순위
  seatArea: string;
  seatSection?: string;
  seatRow?: number;
  seatCol?: number;
  time?: string;
  metrics?: {
    bookingClick?: { reactionMs?: number; misclicks?: number };
    captcha?: { durationMs?: number; wrongCount?: number };
    seatSelection?: {
      durationMs?: number;
      misclicks?: number;
      duplicateSeat?: number;
    };
  };
}

export interface MatchHistory {
  id: number;
  title: string;
  participants: string;
  venue: string;
  venueType: string;
  tags: Array<{ label: string; color: string }>;
  date: string; // YYYY-MM-DD
  time: string; // HH:mm
  mySeatArea?: string;
  mySeatSection?: string; // 내 좌석 구역
  users?: UserRank[];
}

export const mockMatchHistory: MatchHistory[] = [
  {
    id: 1,
    title: "18시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 1명",
    venue: "돔형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "어려움", color: "red" },
      { label: "최대 10명", color: "blue" },
      { label: "봇 3000명", color: "blue" },
    ],
    date: "2024-01-20",
    time: "18:00",
    mySeatArea: "4-7",
    mySeatSection: "A",
    users: [
      {
        id: 0,
        nickname: "나",
        rank: 1, // 전체 순위 (봇 3000명 + 나 포함)
        rankAmongBots: 1, // 봇 3000명 중에서의 순위
        rankAmongUsers: 1, // 사람 1명 중에서의 순위
        seatArea: "4-7",
        seatSection: "A",
        seatRow: 4,
        seatCol: 7,
        time: "04",
      },
    ],
  },
  {
    id: 2,
    title: "20시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 8명",
    venue: "오픈형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "보통", color: "green" },
      { label: "최대 15명", color: "blue" },
      { label: "봇 2000명", color: "blue" },
    ],
    date: "2024-01-18",
    time: "20:00",
    mySeatArea: "5-8",
    mySeatSection: "B",
    users: [
      {
        id: 1,
        nickname: "김철수",
        rank: 1, // 전체 순위 (봇 + 사람)
        rankAmongBots: 1, // 봇들 중에서의 순위
        rankAmongUsers: 1, // 사용자들 중에서의 순위
        seatArea: "2-5",
        seatSection: "A",
        seatRow: 2,
        seatCol: 5,
        time: "03",
        metrics: {
          bookingClick: { reactionMs: 1520, misclicks: 0 },
          captcha: { durationMs: 16800, wrongCount: 0 },
          seatSelection: { durationMs: 38100, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 2,
        nickname: "이영희",
        rank: 2,
        rankAmongBots: 2,
        rankAmongUsers: 2,
        seatArea: "6-3",
        seatSection: "B",
        seatRow: 6,
        seatCol: 3,
        time: "07",
        metrics: {
          bookingClick: { reactionMs: 2100, misclicks: 1 },
          captcha: { durationMs: 22000, wrongCount: 1 },
          seatSelection: { durationMs: 48200, misclicks: 1, duplicateSeat: 0 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 3, // 전체 순위
        rankAmongBots: 3, // 봇들 중에서의 순위
        rankAmongUsers: 3, // 사용자들 중에서의 순위
        seatArea: "5-8",
        seatSection: "B",
        seatRow: 5,
        seatCol: 8,
        time: "11",
        metrics: {
          bookingClick: { reactionMs: 2560, misclicks: 3 },
          captcha: { durationMs: 23010, wrongCount: 3 },
          seatSelection: { durationMs: 63210, misclicks: 3, duplicateSeat: 2 },
        },
      },
      {
        id: 3,
        nickname: "박민수",
        rank: 4,
        rankAmongBots: 4,
        rankAmongUsers: 4,
        seatArea: "3-9",
        seatSection: "A",
        seatRow: 3,
        seatCol: 9,
        time: "15",
        metrics: {
          bookingClick: { reactionMs: 2800, misclicks: 2 },
          captcha: { durationMs: 24000, wrongCount: 2 },
          seatSelection: { durationMs: 55000, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 4,
        nickname: "최지영",
        rank: 5,
        rankAmongBots: 5,
        rankAmongUsers: 5,
        seatArea: "4-11",
        seatSection: "C",
        seatRow: 4,
        seatCol: 11,
        time: "18",
        metrics: {
          bookingClick: { reactionMs: 3200, misclicks: 4 },
          captcha: { durationMs: 35000, wrongCount: 3 },
          seatSelection: { durationMs: 78000, misclicks: 4, duplicateSeat: 2 },
        },
      },
      {
        id: 5,
        nickname: "강동원",
        rank: 6,
        seatArea: "1-7",
        seatSection: "A",
        seatRow: 1,
        seatCol: 7,
        time: "22",
        metrics: {
          bookingClick: { reactionMs: 2900, misclicks: 2 },
          captcha: { durationMs: 28000, wrongCount: 2 },
          seatSelection: { durationMs: 68000, misclicks: 3, duplicateSeat: 1 },
        },
      },
      {
        id: 6,
        nickname: "신혜선",
        rank: 7,
        seatArea: "7-2",
        seatSection: "B",
        seatRow: 7,
        seatCol: 2,
        time: "26",
        metrics: {
          bookingClick: { reactionMs: 3900, misclicks: 5 },
          captcha: { durationMs: 42000, wrongCount: 4 },
          seatSelection: { durationMs: 92000, misclicks: 6, duplicateSeat: 3 },
        },
      },
      {
        id: 7,
        nickname: "장기철",
        rank: 8,
        seatArea: "8-6",
        seatSection: "C",
        seatRow: 8,
        seatCol: 6,
        time: "30",
        metrics: {
          bookingClick: { reactionMs: 3100, misclicks: 3 },
          captcha: { durationMs: 32000, wrongCount: 3 },
          seatSelection: { durationMs: 72000, misclicks: 3, duplicateSeat: 2 },
        },
      },
    ],
  },
  {
    id: 3,
    title: "15시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 3명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "쉬움", color: "green" },
      { label: "최대 20명", color: "blue" },
      { label: "봇 1500명", color: "blue" },
    ],
    date: "2024-01-22",
    time: "15:00",
    mySeatArea: "6-5",
    mySeatSection: "A",
    users: [
      {
        id: 1,
        nickname: "정성호",
        rank: 1,
        seatArea: "2-8",
        seatSection: "A",
        seatRow: 2,
        seatCol: 8,
        time: "04",
        metrics: {
          bookingClick: { reactionMs: 1800, misclicks: 0 },
          captcha: { durationMs: 19500, wrongCount: 1 },
          seatSelection: { durationMs: 41200, misclicks: 1, duplicateSeat: 0 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 2,
        seatArea: "6-5",
        seatSection: "A",
        seatRow: 6,
        seatCol: 5,
        time: "08",
        metrics: {
          bookingClick: { reactionMs: 2680, misclicks: 2 },
          captcha: { durationMs: 24100, wrongCount: 2 },
          seatSelection: { durationMs: 64500, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 2,
        nickname: "윤수진",
        rank: 3,
        seatArea: "4-3",
        seatSection: "B",
        seatRow: 4,
        seatCol: 3,
        time: "12",
        metrics: {
          bookingClick: { reactionMs: 3200, misclicks: 3 },
          captcha: { durationMs: 28000, wrongCount: 3 },
          seatSelection: { durationMs: 71000, misclicks: 3, duplicateSeat: 2 },
        },
      },
    ],
  },
  {
    id: 4,
    title: "22시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 5명",
    venue: "오픈형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "보통", color: "green" },
      { label: "최대 12명", color: "blue" },
      { label: "봇 5000명", color: "blue" },
    ],
    date: "2024-01-19",
    time: "22:00",
    mySeatArea: "3-6",
    mySeatSection: "B",
    users: [
      {
        id: 1,
        nickname: "송지혜",
        rank: 1,
        seatArea: "1-10",
        seatSection: "A",
        seatRow: 1,
        seatCol: 10,
        time: "06",
        metrics: {
          bookingClick: { reactionMs: 1650, misclicks: 0 },
          captcha: { durationMs: 18800, wrongCount: 0 },
          seatSelection: { durationMs: 40200, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 2,
        nickname: "임수현",
        rank: 2,
        seatArea: "5-7",
        seatSection: "B",
        seatRow: 5,
        seatCol: 7,
        time: "13",
        metrics: {
          bookingClick: { reactionMs: 2350, misclicks: 2 },
          captcha: { durationMs: 26200, wrongCount: 2 },
          seatSelection: { durationMs: 55300, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 3,
        seatArea: "3-6",
        seatSection: "B",
        seatRow: 3,
        seatCol: 6,
        time: "18",
        metrics: {
          bookingClick: { reactionMs: 2820, misclicks: 3 },
          captcha: { durationMs: 27800, wrongCount: 3 },
          seatSelection: { durationMs: 67100, misclicks: 4, duplicateSeat: 2 },
        },
      },
      {
        id: 3,
        nickname: "조한솔",
        rank: 4,
        seatArea: "2-5",
        seatSection: "A",
        seatRow: 2,
        seatCol: 5,
        time: "24",
        metrics: {
          bookingClick: { reactionMs: 3100, misclicks: 3 },
          captcha: { durationMs: 34200, wrongCount: 3 },
          seatSelection: { durationMs: 74200, misclicks: 4, duplicateSeat: 2 },
        },
      },
      {
        id: 4,
        nickname: "백민준",
        rank: 5,
        seatArea: "8-2",
        seatSection: "C",
        seatRow: 8,
        seatCol: 2,
        time: "30",
        metrics: {
          bookingClick: { reactionMs: 3500, misclicks: 4 },
          captcha: { durationMs: 39800, wrongCount: 4 },
          seatSelection: { durationMs: 81400, misclicks: 5, duplicateSeat: 3 },
        },
      },
    ],
  },
  {
    id: 5,
    title: "14시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 2명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "어려움", color: "red" },
      { label: "최대 8명", color: "blue" },
      { label: "봇 3500명", color: "blue" },
    ],
    date: "2024-01-23",
    time: "14:00",
    mySeatArea: "7-9",
    mySeatSection: "A",
    users: [
      {
        id: 1,
        nickname: "이도현",
        rank: 1,
        seatArea: "2-4",
        seatSection: "A",
        seatRow: 2,
        seatCol: 4,
        time: "03",
        metrics: {
          bookingClick: { reactionMs: 1720, misclicks: 0 },
          captcha: { durationMs: 18200, wrongCount: 0 },
          seatSelection: { durationMs: 39500, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 2,
        seatArea: "7-9",
        seatSection: "A",
        seatRow: 7,
        seatCol: 9,
        time: "07",
        metrics: {
          bookingClick: { reactionMs: 2750, misclicks: 2 },
          captcha: { durationMs: 25400, wrongCount: 2 },
          seatSelection: { durationMs: 65800, misclicks: 2, duplicateSeat: 1 },
        },
      },
    ],
  },
  {
    id: 6,
    title: "16시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 1명",
    venue: "오픈형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "쉬움", color: "green" },
      { label: "최대 5명", color: "blue" },
      { label: "봇 1000명", color: "blue" },
    ],
    date: "2024-01-17",
    time: "16:00",
    mySeatArea: "3-12",
    mySeatSection: "B",
    users: [
      {
        id: 0,
        nickname: "나",
        rank: 1,
        seatArea: "3-12",
        seatSection: "B",
        seatRow: 3,
        seatCol: 12,
        time: "04",
      },
    ],
  },
  {
    id: 7,
    title: "19시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 4명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "보통", color: "green" },
      { label: "최대 18명", color: "blue" },
      { label: "봇 2500명", color: "blue" },
    ],
    date: "2024-01-21",
    time: "19:00",
    mySeatArea: "4-2",
    mySeatSection: "C",
    users: [
      {
        id: 1,
        nickname: "김서현",
        rank: 1,
        seatArea: "1-9",
        seatSection: "A",
        seatRow: 1,
        seatCol: 9,
        time: "05",
        metrics: {
          bookingClick: { reactionMs: 1900, misclicks: 1 },
          captcha: { durationMs: 21000, wrongCount: 1 },
          seatSelection: { durationMs: 42800, misclicks: 1, duplicateSeat: 0 },
        },
      },
      {
        id: 2,
        nickname: "최우진",
        rank: 2,
        seatArea: "6-4",
        seatSection: "B",
        seatRow: 6,
        seatCol: 4,
        time: "11",
        metrics: {
          bookingClick: { reactionMs: 2450, misclicks: 2 },
          captcha: { durationMs: 27200, wrongCount: 2 },
          seatSelection: { durationMs: 58900, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 3,
        nickname: "박하늘",
        rank: 3,
        seatArea: "3-11",
        seatSection: "A",
        seatRow: 3,
        seatCol: 11,
        time: "17",
        metrics: {
          bookingClick: { reactionMs: 2950, misclicks: 3 },
          captcha: { durationMs: 31800, wrongCount: 3 },
          seatSelection: { durationMs: 68400, misclicks: 3, duplicateSeat: 1 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 4,
        seatArea: "4-2",
        seatSection: "C",
        seatRow: 4,
        seatCol: 2,
        time: "21",
        metrics: {
          bookingClick: { reactionMs: 3300, misclicks: 3 },
          captcha: { durationMs: 36200, wrongCount: 3 },
          seatSelection: { durationMs: 75200, misclicks: 4, duplicateSeat: 2 },
        },
      },
    ],
  },
  {
    id: 8,
    title: "21시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 1명",
    venue: "오픈형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "어려움", color: "red" },
      { label: "최대 7명", color: "blue" },
      { label: "봇 2800명", color: "blue" },
    ],
    date: "2024-01-15",
    time: "21:00",
    mySeatArea: "8-3",
    mySeatSection: "C",
    users: [
      {
        id: 0,
        nickname: "나",
        rank: 1,
        seatArea: "8-3",
        seatSection: "C",
        seatRow: 8,
        seatCol: 3,
        time: "05",
      },
    ],
  },
  {
    id: 9,
    title: "13시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 6명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "쉬움", color: "green" },
      { label: "최대 25명", color: "blue" },
      { label: "봇 1800명", color: "blue" },
    ],
    date: "2024-01-24",
    time: "13:00",
    mySeatArea: "1-6",
    mySeatSection: "A",
    users: [
      {
        id: 1,
        nickname: "안지우",
        rank: 1,
        seatArea: "3-10",
        seatSection: "A",
        seatRow: 3,
        seatCol: 10,
        time: "04",
        metrics: {
          bookingClick: { reactionMs: 1680, misclicks: 0 },
          captcha: { durationMs: 17500, wrongCount: 0 },
          seatSelection: { durationMs: 38800, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 2,
        seatArea: "1-6",
        seatSection: "A",
        seatRow: 1,
        seatCol: 6,
        time: "09",
        metrics: {
          bookingClick: { reactionMs: 2640, misclicks: 2 },
          captcha: { durationMs: 23800, wrongCount: 2 },
          seatSelection: { durationMs: 63800, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 2,
        nickname: "조민서",
        rank: 3,
        seatArea: "5-5",
        seatSection: "B",
        seatRow: 5,
        seatCol: 5,
        time: "14",
        metrics: {
          bookingClick: { reactionMs: 3050, misclicks: 3 },
          captcha: { durationMs: 29200, wrongCount: 3 },
          seatSelection: { durationMs: 69800, misclicks: 3, duplicateSeat: 1 },
        },
      },
      {
        id: 3,
        nickname: "홍길동",
        rank: 4,
        seatArea: "7-8",
        seatSection: "C",
        seatRow: 7,
        seatCol: 8,
        time: "20",
        metrics: {
          bookingClick: { reactionMs: 3420, misclicks: 3 },
          captcha: { durationMs: 33500, wrongCount: 3 },
          seatSelection: { durationMs: 74200, misclicks: 4, duplicateSeat: 2 },
        },
      },
      {
        id: 4,
        nickname: "이순신",
        rank: 5,
        seatArea: "2-2",
        seatSection: "A",
        seatRow: 2,
        seatCol: 2,
        time: "26",
        metrics: {
          bookingClick: { reactionMs: 3650, misclicks: 4 },
          captcha: { durationMs: 38200, wrongCount: 4 },
          seatSelection: { durationMs: 81200, misclicks: 5, duplicateSeat: 3 },
        },
      },
      {
        id: 5,
        nickname: "김유신",
        rank: 6,
        seatArea: "8-4",
        seatSection: "C",
        seatRow: 8,
        seatCol: 4,
        time: "32",
        metrics: {
          bookingClick: { reactionMs: 3880, misclicks: 4 },
          captcha: { durationMs: 41800, wrongCount: 4 },
          seatSelection: { durationMs: 88200, misclicks: 6, duplicateSeat: 3 },
        },
      },
    ],
  },
  {
    id: 10,
    title: "17시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 2명",
    venue: "오픈형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "보통", color: "green" },
      { label: "최대 9명", color: "blue" },
      { label: "봇 4000명", color: "blue" },
    ],
    date: "2024-01-16",
    time: "17:00",
    mySeatArea: "6-10",
    mySeatSection: "B",
    users: [
      {
        id: 1,
        nickname: "손석현",
        rank: 1,
        seatArea: "2-7",
        seatSection: "A",
        seatRow: 2,
        seatCol: 7,
        time: "02",
        metrics: {
          bookingClick: { reactionMs: 1580, misclicks: 0 },
          captcha: { durationMs: 17100, wrongCount: 0 },
          seatSelection: { durationMs: 37400, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 2,
        seatArea: "6-10",
        seatSection: "B",
        seatRow: 6,
        seatCol: 10,
        time: "06",
        metrics: {
          bookingClick: { reactionMs: 2720, misclicks: 3 },
          captcha: { durationMs: 26600, wrongCount: 3 },
          seatSelection: { durationMs: 68200, misclicks: 3, duplicateSeat: 1 },
        },
      },
    ],
  },
  {
    id: 11,
    title: "23시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 1명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "쉬움", color: "green" },
      { label: "최대 6명", color: "blue" },
      { label: "봇 1200명", color: "blue" },
    ],
    date: "2024-01-14",
    time: "23:00",
    mySeatArea: "5-1",
    mySeatSection: "D",
    users: [
      {
        id: 0,
        nickname: "나",
        rank: 1,
        seatArea: "5-1",
        seatSection: "D",
        seatRow: 5,
        seatCol: 1,
        time: "03",
      },
    ],
  },
  {
    id: 12,
    title: "12시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 7명",
    venue: "오픈형 콘서트장",
    venueType: "커스텀",
    tags: [
      { label: "어려움", color: "red" },
      { label: "최대 30명", color: "blue" },
      { label: "봇 6000명", color: "blue" },
    ],
    date: "2024-01-13",
    time: "12:00",
    mySeatArea: "2-11",
    mySeatSection: "C",
    users: [
      {
        id: 1,
        nickname: "문소희",
        rank: 1,
        seatArea: "1-3",
        seatSection: "A",
        seatRow: 1,
        seatCol: 3,
        time: "06",
        metrics: {
          bookingClick: { reactionMs: 1650, misclicks: 0 },
          captcha: { durationMs: 18500, wrongCount: 0 },
          seatSelection: { durationMs: 40200, misclicks: 0, duplicateSeat: 0 },
        },
      },
      {
        id: 2,
        nickname: "차민석",
        rank: 2,
        seatArea: "4-6",
        seatSection: "B",
        seatRow: 4,
        seatCol: 6,
        time: "13",
        metrics: {
          bookingClick: { reactionMs: 2400, misclicks: 2 },
          captcha: { durationMs: 27800, wrongCount: 2 },
          seatSelection: { durationMs: 61800, misclicks: 2, duplicateSeat: 1 },
        },
      },
      {
        id: 3,
        nickname: "정혜영",
        rank: 3,
        seatArea: "5-10",
        seatSection: "B",
        seatRow: 5,
        seatCol: 10,
        time: "20",
        metrics: {
          bookingClick: { reactionMs: 2850, misclicks: 2 },
          captcha: { durationMs: 32400, wrongCount: 3 },
          seatSelection: { durationMs: 69400, misclicks: 3, duplicateSeat: 1 },
        },
      },
      {
        id: 4,
        nickname: "손민우",
        rank: 4,
        seatArea: "7-4",
        seatSection: "C",
        seatRow: 7,
        seatCol: 4,
        time: "27",
        metrics: {
          bookingClick: { reactionMs: 3200, misclicks: 3 },
          captcha: { durationMs: 35800, wrongCount: 3 },
          seatSelection: { durationMs: 76800, misclicks: 4, duplicateSeat: 2 },
        },
      },
      {
        id: 5,
        nickname: "김도영",
        rank: 5,
        seatArea: "8-12",
        seatSection: "C",
        seatRow: 8,
        seatCol: 12,
        time: "34",
        metrics: {
          bookingClick: { reactionMs: 3650, misclicks: 3 },
          captcha: { durationMs: 41200, wrongCount: 4 },
          seatSelection: { durationMs: 84200, misclicks: 5, duplicateSeat: 3 },
        },
      },
      {
        id: 0,
        nickname: "나",
        rank: 6,
        seatArea: "2-11",
        seatSection: "C",
        seatRow: 2,
        seatCol: 11,
        time: "40",
        metrics: {
          bookingClick: { reactionMs: 3800, misclicks: 4 },
          captcha: { durationMs: 45200, wrongCount: 4 },
          seatSelection: { durationMs: 96200, misclicks: 5, duplicateSeat: 3 },
        },
      },
      {
        id: 6,
        nickname: "이수진",
        rank: 7,
        seatArea: "3-1",
        seatSection: "A",
        seatRow: 3,
        seatCol: 1,
        time: "47",
        metrics: {
          bookingClick: { reactionMs: 4200, misclicks: 5 },
          captcha: { durationMs: 49800, wrongCount: 5 },
          seatSelection: { durationMs: 102200, misclicks: 6, duplicateSeat: 4 },
        },
      },
    ],
  },
  {
    id: 13,
    title: "11시에 티켓팅하실 분 모집합니다",
    participants: "참가인원 1명",
    venue: "돔형 콘서트장",
    venueType: "자동",
    tags: [
      { label: "보통", color: "green" },
      { label: "최대 4명", color: "blue" },
      { label: "봇 800명", color: "blue" },
    ],
    date: "2024-01-25",
    time: "11:00",
    mySeatArea: "2-9",
    mySeatSection: "A",
    users: [
      {
        id: 0,
        nickname: "나",
        rank: 1,
        seatArea: "2-9",
        seatSection: "A",
        seatRow: 2,
        seatCol: 9,
        time: "02",
      },
    ],
  },
];
